name: hinerv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core environment
  - python=3.9
  - numpy<2.0

  # PyTorch with specific CUDA version for ITEC server (CUDA 12.2 Driver)
  - pytorch==2.1.0
  - torchvision==0.16.0
  - pytorch-cuda=12.1

  # Other Conda dependencies
  - ffmpeg
  - pytorch-msssim==1.0.0
  - timm==0.9.7
  - git
  - pip

  # Pip-specific dependencies
  - pip:
    - accelerate==0.23.0
    - deepspeed==0.11.1
    - torchac==0.9.3
