name: hinerv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core environment
  - python=3.9
  - numpy<2.0

  # PyTorch and its CUDA runtime dependency
  - pytorch==2.1.0
  - torchvision==0.16.0
  - pytorch-cuda=12.1

  # The CUDA Compiler Toolkit - THIS IS THE FIX
  # This package provides the actual nvcc compiler needed by deepspeed
  - cuda-toolkit=12.1

  # Other Conda dependencies
  - ffmpeg
  - pytorch-msssim==1.0.0
  - timm==0.9.7
  - git
  - pip
